import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from "next/font/google";
import { Landing } from "@/components/Landing";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${montserrat.className}`}
      >
        <Landing />
        {children}
      </body>
    </html>
  );
}
